--
-- тЮИК ЯЦЕМЕПХПНБЮМ Я ОНЛНЫЭЧ SQLiteStudio v3.2.1 Б оР ДЕЙ 21 10:05:01 2018
--
-- хЯОНКЭГНБЮММЮЪ ЙНДХПНБЙЮ РЕЙЯРЮ: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- рЮАКХЖЮ: oksmt
CREATE TABLE oksmt (KOD varchar(3) NOT NULL DEFAULT '', ABC2 varchar(2), ABC3 varchar(3), ANAIM varchar(40), KRNAIM varchar(40), NAIM varchar(62), KOD_AR varchar(20), IMPORT REAL, S_IMPORT REAL, PRIMARY KEY (KOD));
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('004', 'AF', 'AFG', 'AFGHANISTAN', 'ютцюмхярюм', 'оепеундмне хякюляйне цнясдюпярбн ютцюмхярюм', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('008', 'AL', 'ALB', 'ALBANIA', 'юкаюмхъ', 'пеяосакхйю юкаюмхъ', '40,96,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('031', 'AZ', 'AZE', 'AZERBAIJAN', 'югепаюидфюм', 'пеяосакхйю югепаюидфюм', '10', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('032', 'AR', 'ARG', 'ARGENTINA', 'юпцемрхмю', 'юпцемрхмяйюъ пеяосакхйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('036', 'AU', 'AUS', 'AUSTRALIA', 'юбярпюкхъ', 'юбярпюкхъ', '20,50,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('040', 'AT', 'AUT', 'AUSTRIA', 'юбярпхъ', 'юбярпхияйюъ пеяосакхйю', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('050', 'BD', 'BGD', 'BANGLADESH', 'аюмцкюдеь', 'мюпндмюъ пеяосакхйю аюмцкюдеь', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('056', 'BE', 'BEL', 'BELGIUM', 'аекэцхъ', 'йнпнкебярбн аекэцхъ', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('072', 'BW', 'BWA', 'BOTSWANA', 'анрябюмю', 'пеяосакхйю анрябюмю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('076', 'BR', 'BRA', 'BRAZIL', 'апюгхкхъ', 'тедепюрхбмюъ пеяосакхйю апюгхкхъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('108', 'BI', 'BDI', 'BURUNDI', 'аспсмдх', 'пеяосакхйю аспсмдх', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('116', 'KH', 'KHM', 'CAMBODIA', 'йюландфю', 'йнпнкебярбн йюландфю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('120', 'CM', 'CMR', 'CAMEROON', 'йюлепсм', 'пеяосакхйю йюлепсм', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('124', 'CA', 'CAN', 'CANADA', 'йюмюдю', 'йюмюдю', '20,50,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('144', 'LK', 'LKA', 'SRI LANKA', 'ьпх-кюмйю', 'делнйпюрхвеяйюъ янжхюкхярхвеяйюъ пеяосакхйю ьпх-кюмйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('148', 'TD', 'TCD', 'CHAD', 'вюд', 'пеяосакхйю вюд', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('156', 'CN', 'CHN', 'CHINA', 'йхрюи', 'йхрюияйюъ мюпндмюъ пеяосакхйю', '50,99,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('170', 'CO', 'COL', 'COLOMBIA', 'йнкслахъ', 'пеяосакхйю йнкслахъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('178', 'CG', 'COG', 'CONGO', 'йнмцн', 'пеяосакхйю йнмцн', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('188', 'CR', 'CRI', 'COSTA RICA', 'йнярю-пхйю', 'пеяосакхйю йнярю-пхйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('204', 'BJ', 'BEN', 'BENIN', 'аемхм', 'пеяосакхйю аемхм', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('208', 'DK', 'DNK', 'DENMARK', 'дюмхъ', 'йнпнкебярбн дюмхъ', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('222', 'SV', 'SLV', 'EL SALVADOR', 'щкэ-яюкэбюднп', 'пеяосакхйю щкэ-яюкэбюднп', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('231', 'ET', 'ETH', 'ETHIOPIA', 'щтхнохъ', 'тедепюрхбмюъ делнйпюрхвеяйюъ пеяосакхйю щтхнохъ', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('234', 'FO', 'FRO', 'FAROE ISLANDS', 'тюпепяйхе нярпнбю', 'тюпепяйхе нярпнбю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('246', 'FI', 'FIN', 'FINLAND', 'тхмкъмдхъ', 'тхмкъмдяйюъ пеяосакхйю', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('250', 'FR', 'FRA', 'FRANCE', 'тпюмжхъ', 'тпюмжсгяйюъ пеяосакхйю', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('262', 'DJ', 'DJI', 'DJIBOUTI', 'дфхасрх', 'пеяосакхйю дфхасрх', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('276', 'DE', 'DEU', 'GERMANY', 'цеплюмхъ', 'тедепюрхбмюъ пеяосакхйю цеплюмхъ', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('288', 'GH', 'GHA', 'GHANA', 'цюмю', 'пеяосакхйю цюмю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('300', 'GR', 'GRC', 'GREECE', 'цпежхъ', 'цпевеяйюъ пеяосакхйю', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('308', 'GD', 'GRD', 'GRENADA', 'цпемюдю', 'цпемюдю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('324', 'GN', 'GIN', 'GUINEA', 'цбхмеъ', 'цбхмеияйюъ пеяосакхйю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('328', 'GY', 'GUY', 'GUYANA', 'цюиюмю', 'пеяосакхйю цюиюмю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('340', 'HN', 'HND', 'HONDURAS', 'цнмдспюя', 'пеяосакхйю цнмдспюя', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('352', 'IS', 'ISL', 'ICELAND', 'хякюмдхъ', 'пеяосакхйю хякюмдхъ', '22,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('356', 'IN', 'IND', 'INDIA', 'хмдхъ', 'пеяосакхйю хмдхъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('368', 'IQ', 'IRQ', 'IRAQ', 'хпюй', 'пеяосакхйю хпюй', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('372', 'IE', 'IRL', 'IRELAND', 'хпкюмдхъ', 'хпкюмдхъ', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('380', 'IT', 'ITA', 'ITALY', 'хрюкхъ', 'хрюкэъмяйюъ пеяосакхйю', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('388', 'JM', 'JAM', 'JAMAICA', 'ълюийю', 'ълюийю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('392', 'JP', 'JPN', 'JAPAN', 'ъонмхъ', 'ъонмхъ', '20,50', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('404', 'KE', 'KEN', 'KENYA', 'йемхъ', 'пеяосакхйю йемхъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('408', 'KP', 'PRK', 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF', 'йнпеъ, мюпндмн-делнйпюрхв. пеяосакхйю', 'йнпеияйюъ мюпндмн-делнйпюрхвеяйюъ пеяосакхйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('410', 'KR', 'KOR', 'KOREA,REPUBLIC OF', 'йнпеъ, пеяосакхйю', 'пеяосакхйю йнпеъ', '50,20,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('414', 'KW', 'KWT', 'KUWAIT', 'йсбеир', 'цнясдюпярбн йсбеир', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('418', 'LA', 'LAO', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'кюняяйюъ мюпндмн-делнй. пеяосакхйю', 'кюняяйюъ мюпндмн-делнйпюрхвеяйюъ пеяосакхйю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('422', 'LB', 'LBN', 'LEBANON', 'кхбюм', 'кхбюмяйюъ пеяосакхйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('428', 'LV', 'LVA', 'LATVIA', 'кюрбхъ', 'кюрбхияйюъ пеяосакхйю', '40,24,21,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('430', 'LR', 'LBR', 'LIBERIA', 'кхаепхъ', 'пеяосакхйю кхаепхъ', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('438', 'LI', 'LIE', 'LIECHTENSTEIN', 'кхуремьреим', 'ймъфеярбн кхуремьреим', '23,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('440', 'LT', 'LTU', 'LITHUANIA', 'кхрбю', 'кхрнбяйюъ пеяосакхйю', '40,24,21,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('442', 'LU', 'LUX', 'LUXEMBOURG', 'кчйяеласпц', 'бекхйне цепжнцярбн кчйяеласпц', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('450', 'MG', 'MDG', 'MADAGASCAR', 'людюцюяйюп', 'пеяосакхйю людюцюяйюп', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('458', 'MY', 'MYS', 'MALAYSIA', 'люкюигхъ', 'люкюигхъ', '50,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('478', 'MR', 'MRT', 'MAURITANIA', 'любпхрюмхъ', 'хякюляйюъ пеяосакхйю любпхрюмхъ', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('480', 'MU', 'MUS', 'MAURITIUS', 'любпхйхи', 'пеяосакхйю любпхйхи', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('484', 'MX', 'MEX', 'MEXICO', 'лейяхйю', 'лейяхйюмяйхе янедхмеммше ьрюрш', '50,20,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('496', 'MN', 'MNG', 'MONGOLIA', 'лнмцнкхъ', 'лнмцнкхъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('498', 'MD', 'MDA', 'MOLDOVA, REPUBLIC OF', 'лнкднбю, пеяосакхйю', 'пеяосакхйю лнкднбю', '10', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('504', 'MA', 'MAR', 'MOROCCO', 'люпнййн', 'йнпнкебярбн люпнййн', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('508', 'MZ', 'MOZ', 'MOZAMBIQUE', 'лнгюлахй', 'пеяосакхйю лнгюлахй', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('512', 'OM', 'OMN', 'OMAN', 'нлюм', 'яскрюмюр нлюм', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('516', 'NA', 'NAM', 'NAMIBIA', 'мюлхахъ', 'пеяосакхйю мюлхахъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('528', 'NL', 'NLD', 'NETHERLANDS', 'мхдепкюмдш', 'йнпнкебярбн мхдепкюмднб', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('554', 'NZ', 'NZL', 'NEW ZEALAND', 'мнбюъ гекюмдхъ', 'мнбюъ гекюмдхъ', '20,50', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('558', 'NI', 'NIC', 'NICARAGUA', 'мхйюпюцсю', 'пеяосакхйю мхйюпюцсю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('578', 'NO', 'NOR', 'NORWAY', 'мнпбецхъ', 'йнпнкебярбн мнпбецхъ', '22,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('586', 'PK', 'PAK', 'PAKISTAN', 'оюйхярюм', 'хякюляйюъ пеяосакхйю оюйхярюм', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('591', 'PA', 'PAN', 'PANAMA', 'оюмюлю', 'пеяосакхйю оюмюлю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('604', 'PE', 'PER', 'PERU', 'оепс', 'пеяосакхйю оепс', '50,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('608', 'PH', 'PHL', 'PHILIPPINES', 'тхкхоохмш', 'пеяосакхйю тхкхоохмш', '50,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('616', 'PL', 'POL', 'POLAND', 'онкэью', 'пеяосакхйю онкэью', '40,20,21,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('620', 'PT', 'PRT', 'PORTUGAL', 'онпрсцюкхъ', 'онпрсцюкэяйюъ пеяосакхйю', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('624', 'GW', 'GNB', 'GUINEA-BISSAU', 'цбхмеъ-ахяюс', 'пеяосакхйю цбхмеъ-ахяюс', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('634', 'QA', 'QAT', 'QATAR', 'йюрюп', 'цнясдюпярбн йюрюп', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('646', 'RW', 'RWA', 'RWANDA', 'псюмдю', 'псюмдхияйюъ пеяосакхйю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('678', 'ST', 'STP', 'SAO TOME AND PRINCIPE', 'яюм-рнле х опхмяхох', 'делнйпюрхвеяйюъ пеяосакхйю яюм-рнле х опхмяхох', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('688', 'RS', 'SRB', 'SERBIA', 'яепахъ', 'пеяосакхйю яепахъ', '40,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('694', 'SL', 'SLE', 'SIERRA LEONE', 'яэеппю-кенме', 'пеяосакхйю яэеппю-кенме', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('702', 'SG', 'SGP', 'SINGAPORE', 'яхмцюосп', 'пеяосакхйю яхмцюосп', '50,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('703', 'SK', 'SVK', 'SLOVAKIA', 'якнбюйхъ', 'якнбюжйюъ пеяосакхйю', '40,21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('704', 'VN', 'VNM', 'VIET NAM', 'бэермюл', 'янжхюкхярхвеяйюъ пеяосакхйю бэермюл', '50,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('710', 'ZA', 'ZAF', 'SOUTH AFRICA', 'чфмюъ ютпхйю', 'чфмн-ютпхйюмяйюъ пеяосакхйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('724', 'ES', 'ESP', 'SPAIN', 'хяоюмхъ', 'йнпнкебярбн хяоюмхъ', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('752', 'SE', 'SWE', 'SWEDEN', 'ьбежхъ', 'йнпнкебярбн ьбежхъ', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('756', 'CH', 'CHE', 'SWITZERLAND', 'ьбеижюпхъ', 'ьбеижюпяйюъ йнмтедепюжхъ', '22,20', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('760', 'SY', 'SYR', 'SYRIA', 'яхпхияйюъ юпюаяйюъ пеяосакхйю', 'яхпхияйюъ юпюаяйюъ пеяосакхйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('764', 'TH', 'THA', 'THAILAND', 'рюхкюмд', 'йнпнкебярбн рюхкюмд', '50,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('788', 'TN', 'TUN', 'TUNISIA', 'рсмхя', 'рсмхяяйюъ пеяосакхйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('792', 'TR', 'TUR', 'TURKEY', 'рспжхъ', 'рспежйюъ пеяосакхйю', '20,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('800', 'UG', 'UGA', 'UGANDA', 'сцюмдю', 'пеяосакхйю сцюмдю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('807', 'MK', 'MKD', 'MACEDONIA', 'пеяосакхйю люйеднмхъ', 'пеяосакхйю люйеднмхъ', '40,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('826', 'GB', 'GBR', 'UK OF GREAT BRITAIN AND NORTHERN IRELAND', 'янедхмеммне йнпнкебярбн', 'янедхмеммне йнпнкебярбн бекхйнапхрюмхх х яебепмни хпкюмдхх', '21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('834', 'TZ', 'TZA', 'TANZANIA', 'рюмгюмхъ, назедхмеммюъ пеяосакхйю', 'назедхмеммюъ пеяосакхйю рюмгюмхъ', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('840', 'US', 'USA', 'UNITED STATES', 'янедхмеммше ьрюрш', 'янедхмеммше ьрюрш юлепхйх', '20,50,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('854', 'BF', 'BFA', 'BURKINA FASO', 'аспйхмю-тюян', 'аспйхмю-тюян', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('858', 'UY', 'URY', 'URUGUAY', 'спсцбюи', 'бнярнвмюъ пеяосакхйю спсцбюи', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('887', 'YE', 'YEM', 'YEMEN', 'иелем', 'иелемяйюъ пеяосакхйю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('894', 'ZM', 'ZMB', 'ZAMBIA', 'гюлахъ', 'пеяосакхйю гюлахъ', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('100', 'BG', 'BGR', 'BULGARIA', 'анкцюпхъ', 'пеяосакхйю анкцюпхъ', '40,21,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('642', 'RO', 'ROU', 'ROMANIA', 'пслшмхъ', 'пслшмхъ', '40,21,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('682', 'SA', 'SAU', 'SAUDI ARABIA', 'яюсднбяйюъ юпюбхъ', 'йнпнкебярбн яюсднбяйюъ юпюбхъ', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('320', 'GT', 'GTM', 'GUATEMALA', 'цбюрелюкю', 'пеяосакхйю цбюрелюкю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('132', 'CV', 'CPV', 'CAPE VERDE', 'йюан-бепде', 'пеяосакхйю йюан-бепде', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('896', 'OS', 'OST', 'REPUBLIC SOUTH OSSETIA', 'чфмюъ няерхъ', 'пеяосакхйю чфмюъ няерхъ', '23,90', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('895', 'AB', 'ABH', 'REPUBLIC ABHAZIA', 'юауюгхъ', 'пеяосакхйю юауюгхъ', '23,90', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('068', 'BO', 'BOL', 'бнLIVIA', 'анкхбхъ, лмнцнмюжхнмюкэмне цнясдюпярбн', 'лмнцнмюжхнмюкэмне цнясдюпярбн анкхбхъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('499', 'ME', 'MNE', 'MONTENEGRO', 'вепмнцнпхъ', 'вепмнцнпхъ', '40,96,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('524', 'NP', 'NPL', 'NEPAL', 'меоюк', 'тедепюрхбмюъ делнйпюрхвеяйюъ пеяосакхйю меоюк', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('268', 'GE', 'GEO', 'GEORGIA', 'цпсгхъ', 'цпсгхъ', '23,90', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('070', 'BA', 'BIH', 'BOSNIA AND HERZEGOWINA', 'анямхъ х цепжецнбхмю', 'анямхъ х цепжецнбхмю', '40,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('196', 'CY', 'CYP', 'CYPRUS', 'йхоп', 'пеяосакхйю йхоп', '21,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('470', 'MT', 'MLT', 'MALTA', 'люкэрю', 'пеяосакхйю люкэрю', '21,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('180', 'CD', 'COD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'йнмцн, делнйпюрхвеяйюъ пеяосакхйю', 'делнйпюрхвеяйюъ пеяосакхйю йнмцн', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('600', 'PY', 'PRY', 'PARAGUAY', 'оюпюцбюи', 'пеяосакхйю оюпюцбюи', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('152', 'CL', 'CHL', 'CHILE', 'вхкх', 'пеяосакхйю вхкх', '50,20,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('233', 'EE', 'EST', 'ESTONIA', 'щярнмхъ', 'щярнмяйюъ пеяосакхйю', '40,24,21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('705', 'SI', 'SVN', 'SLOVENIA', 'якнбемхъ', 'пеяосакхйю якнбемхъ', '40,21,20,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('376', 'IL', 'ISR', 'ISRAEL', 'хгпюхкэ', 'цнясдюпярбн хгпюхкэ', '23,20', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('104', 'MM', 'MMR', 'MYANMAR (BURMA)', 'лэъмлю', 'пеяосакхйю янчгю лэъмлю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('729', 'SD', 'SDN', 'SUDAN', 'ясдюм', 'пеяосакхйю ясдюм', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('304', 'GL', 'GRL', 'GREENLAND', 'цпемкюмдхъ', 'цпемкюмдхъ', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('492', 'MC', 'MCO', 'MONACO', 'лнмюйн', 'ймъфеярбн лнмюйн', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('630', 'PR', 'PRI', 'PUERTO RICO', 'осщпрн-пхйн', 'осщпрн-пхйн', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('860', 'UZ', 'UZB', 'UZBEKISTAN', 'сгаейхярюм', 'пеяосакхйю сгаейхярюм', '10', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('064', 'BT', 'BTN', 'BHUTAN', 'асрюм', 'йнпнкебярбн асрюм', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('548', 'VU', 'VUT', 'VANUATU', 'бюмсюрс', 'пеяосакхйю бюмсюрс', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('332', 'HT', 'HTI', 'HAITI', 'цюхрх', 'пеяосакхйю цюхрх', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('296', 'KI', 'KIR', 'KIRIBATI', 'йхпхаюрх', 'пеяосакхйю йхпхаюрх', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('174', 'KM', 'COM', 'COMOROS', 'йнлнпш', 'янчг йнлнпш', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('454', 'MW', 'MWI', 'MALAWI', 'люкюбх', 'пеяосакхйю люкюбх', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('686', 'SN', 'SEN', 'SENEGAL', 'яемецюк', 'пеяосакхйю яемецюк', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('090', 'SB', 'SLB', 'SOLOMON ISLANDS', 'янкнлнмнбш нярпнбю', 'янкнлнмнбш нярпнбю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('626', 'TL', 'TLS', 'EAST TIMOR', 'рхлнп-кеяре', 'делнйпюрхвеяйюъ пеяосакхйю рхлнп-кеяре', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('768', 'TG', 'TGO', 'TOGO', 'рнцн', 'рнцнкегяйюъ пеяосакхйю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('798', 'TV', 'TUV', 'TUVALU', 'рсбюкс', 'рсбюкс', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('140', 'CF', 'CAF', 'CENTRAL AFRICAN REPUBLIC', 'жемрпюкэмн-ютпхйюмяйюъ пеяосакхйю', 'жемрпюкэмн-ютпхйюмяйюъ пеяосакхйю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('012', 'DZ', 'DZA', 'ALGERIA', 'юкфхп', 'юкфхпяйюъ мюпндмюъ делнйпюрхвеяйюъ пеяосакхйю', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('016', 'AS', 'ASM', 'AMERICAN (EASTERN) SAMOA', 'юлепхйюмяйне яюлню', 'юлепхйюмяйне яюлню', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('660', 'AI', 'AIA', 'ANGUILLA', 'юмцхкэъ', 'юмцхкэъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('020', 'AD', 'AND', 'ANDORRA', 'юмднппю', 'ймъфеярбн юмднппю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('010', 'AQ', 'ATA', 'ANTARCTICA', 'юмрюпйрхдю', 'юмрюпйрхдю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('028', 'AG', 'ATG', 'ANTIGUA AND BARBUDA', 'юмрхцсю х аюпасдю', 'юмрхцсю х аюпасдю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('533', 'AW', 'ABW', 'ARUBA', 'юпсаю', 'юпсаю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('044', 'BS', 'BHS', 'BAHAMAS', 'аюцюлш', 'яндпсфеярбн аюцюлш', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('052', 'BB', 'BRB', 'BARBADOS', 'аюпаюдня', 'аюпаюдня', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('084', 'BZ', 'BLZ', 'BELIZE', 'аекхг', 'аекхг', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('060', 'BM', 'BMU', 'BERMUDA', 'аеплсдш', 'аеплсдш', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('535', 'BQ', 'BES', 'BONAIRE, SAINT EUSTATIUS AND SABA', 'анмщип,яхмр-щярюрхся х яюаю', 'анмщип,яхмр-щярюрхся х яюаю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('086', 'IO', 'IOT', 'BRITISH INDIAN OCEAN TERRITORY', 'апхрюмяйюъ реппхрнпхъ б хмд.нйеюме', 'апхрюмяйюъ реппхрнпхъ б хмдхияйнл нйеюме', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('096', 'BN', 'BRN', 'BRUNEL', 'апсмеи-дюпсяяюкюл', 'апсмеи-дюпсяяюкюл', '50,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('074', 'BV', 'BVT', 'BOUVET ISLAND', 'нярпнб асбе', 'нярпнб асбе', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('312', 'GP', 'GLP', 'GUADELOUPE', 'цбюдексою', 'цбюдексою', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('831', 'GG', 'GGY', 'GUERNSEY', 'цепмях', 'цепмях', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('292', 'GI', 'GIB', 'GIBRALTAR', 'цхапюкрюп', 'цхапюкрюп', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('344', 'HK', 'HKG', 'HONG KONG', 'цнмйнмц', 'яоежхюкэмши юдлхмхярпюрхбмши пецхнм йхрюъ цнмйнмц', '50,99,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('316', 'GU', 'GUM', 'GUAM', 'цсюл', 'цсюл', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('832', 'JE', 'JEY', 'JERSEY', 'дфепях', 'дфепях', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('212', 'DM', 'DMA', 'DOMINICA', 'днлхмхйю', 'яндпсфеярбн днлхмхйх', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('214', 'DO', 'DOM', 'DOMINICAN REPUBLIC', 'днлхмхйюмяйюъ пеяосакхйю', 'днлхмхйюмяйюъ пеяосакхйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('732', 'EH', 'ESH', 'WESTERN SAHARA', 'гюоюдмюъ яюуюпю', 'гюоюдмюъ яюуюпю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('166', 'CC', 'CCK', 'COCOS (KEELING) ISLANDS', 'йнйнянбше (йхкхмц) нярпнбю', 'йнйнянбше (йхкхмц) нярпнбю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('531', 'CW', 'CUW', 'CURACAO', 'йчпюяюн', 'йчпюяюн', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('175', 'YT', 'MYT', 'MAYOTTE', 'люинррю', 'люинррю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('581', 'UM', 'UMI', 'UNITED STATES MINOR OUTLYING ISLANDS', 'люкше рхуннйеюм.нрдюкем.няр-бю я.ь.', 'люкше рхуннйеюмяйхе нрдюкеммше нярпнбю янедхмеммшу ьрюрнб', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('474', 'MQ', 'MTQ', 'MARTINIQUE', 'люпрхмхйю', 'люпрхмхйю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('584', 'MH', 'MHL', 'MARSHALL ISLANDS', 'люпьюккнбш нярпнбю', 'пеяосакхйю люпьюккнбш нярпнбю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('583', 'FM', 'FSM', 'MICRONESIA', 'лхйпнмегхъ, тедепюрхбмше ьрюрш', 'тедепюрхбмше ьрюрш лхйпнмегхх', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('500', 'MS', 'MSR', 'MONTSERRAT', 'лнмряеппюр', 'лнмряеппюр', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('520', 'NR', 'NRU', 'NAURU', 'мюспс', 'пеяосакхйю мюспс', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('570', 'NU', 'NIU', 'NIUE', 'мхсщ', 'мхсщ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('540', 'NC', 'NCL', 'NEW CALEDONIA', 'мнбюъ йюкеднмхъ', 'мнбюъ йюкеднмхъ', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('833', 'IM', 'IMN', 'ISLE OF MAN', 'нярпнб лщм', 'нярпнб лщм', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('574', 'NF', 'NFK', 'NORFOLK ISLAND', 'нярпнб мнптнкй', 'нярпнб мнптнкй', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('162', 'CX', 'CXR', 'CHRISTMAS ISLAND (AUSTRALIA)', 'нярпнб пнфдеярбю', 'нярпнб пнфдеярбю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('334', 'HM', 'HMD', 'HEARD AND MC DONALD ISLANDS', 'нярпнб уепд х нярпнбю люйднмюкэд', 'нярпнб уепд х нярпнбю люйднмюкэд', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('136', 'KY', 'CYM', 'CAYMAN ISLANDS', 'нярпнбю йюилюм', 'нярпнбю йюилюм', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('184', 'CK', 'COK', 'COOK ISLANDS', 'нярпнбю йсйю', 'нярпнбю йсйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('796', 'TC', 'TCA', 'TURKS AND CAICOS ISLANDS', 'нярпнбю репйя х йюийня', 'нярпнбю репйя х йюийня', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('585', 'PW', 'PLW', 'PACIFIC ISLANDS (PALAU)', 'оюкюс', 'пеяосакхйю оюкюс', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('336', 'VA', 'VAT', 'VATICAN (HOLY SEE)', 'оюояйхи опеярнк(цня.-цнпнд бюрхйюм)', 'оюояйхи опеярнк (цнясдюпярбн-цнпнд бюрхйюм)', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('612', 'PN', 'PCN', 'PITCAIRN', 'охрйепм', 'охрйепм', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('638', 'RE', 'REU', 'REUNION', 'печмэнм', 'печмэнм', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('674', 'SM', 'SMR', 'SAN MARINO', 'яюм-люпхмн', 'пеяосакхйю яюм-люпхмн', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('654', 'SH', 'SHN', 'ST. HELENA', 'яб.екемю,н.бнгмея.,рпхярюм-дю-йсмэъ', 'ябърюъ екемю,нярпнб бнгмеяемхъ,рпхярюм-дю-йсмэъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('580', 'MP', 'MNP', 'NORTHERN MARIANA ISLANDS', 'яебепмше люпхюмяйхе нярпнбю', 'яндпсфеярбн яебепмшу люпхюмяйху нярпнбнб', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('690', 'SC', 'SYC', 'SEYCHELLES', 'яеиьекш', 'пеяосакхйю яеиьекш', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('652', 'BL', 'BLM', 'SAINT BARTHELEMY', 'яем-аюпрекелх', 'яем-аюпрекелх', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('534', 'SX', 'SXM', 'SINT MAARTEN (DUTCH PART)', 'яем-люпрем(мхдепкюмдяйюъ вюярэ)', 'яем-люпрем(мхдепкюмдяйюъ вюярэ)', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('666', 'PM', 'SPM', 'SAINT PIERRE AND MIQUELON', 'яемр-оэеп х лхйекнм', 'яемр-оэеп х лхйекнм', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('670', 'VC', 'VCT', 'SAINT VINCENT AND THE GRENADINES', 'яемр-бхмяемр х цпемюдхмш', 'яемр-бхмяемр х цпемюдхмш', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('659', 'KN', 'KNA', 'SAINT KITTS AND NEVIS', 'яемр-йхря х мебхя', 'яемр-йхря х мебхя', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('662', 'LC', 'LCA', 'SAINT LUCIA', 'яемр-кчяхъ', 'яемр-кчяхъ', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('740', 'SR', 'SUR', 'SURINAME', 'яспхмюл', 'пеяосакхйю яспхмюл', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('772', 'TK', 'TKL', 'TOKELAU', 'рнйекюс', 'рнйекюс', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('776', 'TO', 'TON', 'TONGA', 'рнмцю', 'йнпнкебярбн рнмцю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('876', 'WF', 'WLF', 'WALLIS AND FUTUNA ISLANDS', 'снккхя х тсрсмю', 'снккхя х тсрсмю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('242', 'FJ', 'FJI', 'FIJI', 'тхдфх', 'пеяосакхйю  тхдфх', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('238', 'FK', 'FLK', 'FALKLAND ISLANDS (MALVINAS)', 'тнкйкемдяйхе нярпнбю (люкэбхмяйхе)', 'тнкйкемдяйхе нярпнбю (люкэбхмяйхе)', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('254', 'GF', 'GUF', 'FRENCH GUIANA', 'тпюмжсгяйюъ цбхюмю', 'тпюмжсгяйюъ цбхюмю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('258', 'PF', 'PYF', 'FRENCH POLYNESIA', 'тпюмжсгяйюъ онкхмегхъ', 'тпюмжсгяйюъ онкхмегхъ', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('260', 'TF', 'ATF', 'FRENCH SOUTHERN TERRITORIES', 'тпюмжсгяйхе чфмше реппхрнпхх', 'тпюмжсгяйхе чфмше реппхрнпхх', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('744', 'SJ', 'SJM', 'SVALBARD AND JAN MAYEN ISLANDS', 'ьохжаепцем х ъм люием', 'ьохжаепцем х ъм люием', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('248', 'AX', 'ALA', 'ALAND ISLANDS', 'щкюмдяйхе нярпнбю', 'щкюмдяйхе нярпнбю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('239', 'GS', 'SGS', 'SOUTH GEORGIA AND THE S.SANDWICH ISLANDS', 'чфм.дфнпдфхъ х чфм.яюмдбхв.нярпнбю', 'чфмюъ дфнпдфхъ х чфмше яюмдбхвебш нярпнбю', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('348', 'HU', 'HUN', 'HUNGARY', 'бемцпхъ', 'бемцпхъ', '40,20,21,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('232', 'ER', 'ERI', 'ERITREA', 'щпхрпеъ', 'цнясдюпярбн щпхрпеъ', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('024', 'AO', 'AGO', 'ANGOLA', 'юмцнкю', 'пеяосакхйю юмцнкю', '23,30,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('218', 'EC', 'ECU', 'ECUADOR', 'щйбюднп', 'пеяосакхйю щйбюднп', '23,30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('275', 'PS', 'PSE', 'STATE OF PALESTINE', 'оюкеярхмю, цнясдюпярбн', 'цнясдюпярбн оюкеярхмю', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('818', 'EG', 'EGY', 'EGYPT', 'ецхоер', 'юпюаяйюъ пеяосакхйю ецхоер', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('716', 'ZW', 'ZWE', 'ZIMBABWE', 'гхлаюабе', 'пеяосакхйю гхлаюабе', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('400', 'JO', 'JOR', 'JORDAN', 'хнпдюмхъ', 'хнпдюмяйне уюьхлхряйне йнпнкебярбн', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('192', 'CU', 'CUB', 'CUBA', 'йсаю', 'пеяосакхйю йсаю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('426', 'LS', 'LSO', 'LESOTHO', 'кеянрн', 'йнпнкебярбн кеянрн', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('562', 'NE', 'NER', 'NIGER', 'мхцеп', 'пеяосакхйю мхцеп', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('566', 'NG', 'NGA', 'NIGERIA', 'мхцепхъ', 'тедепюрхбмюъ пеяосакхйю мхцепхъ', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('780', 'TT', 'TTO', 'TRINIDAD AND TOBAGO', 'рпхмхдюд х рнаюцн', 'пеяосакхйю рпхмхдюд х рнаюцн', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('446', 'MO', 'MAC', 'MACAU', 'люйюн', 'яоежхюкэмши юдлхмхярпюрхбмши пецхнм йхрюъ люйюн', '23,99', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('784', 'AE', 'ARE', 'UNITED ARAB EMIRATES', 'назедхмеммше юпюаяйхе щлхпюрш', 'назедхмеммше юпюаяйхе щлхпюрш', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('158', 'TW', 'TWN', 'TAIWAN,PROVINCE OF CHINA', 'рюибюмэ (йхрюи)', 'рюибюмэ (йхрюи)', '50,99,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('466', 'ML', 'MLI', 'MALI', 'люкх', 'пеяосакхйю люкх', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('048', 'BH', 'BHR', 'BAHRAIN', 'аюупеим', 'йнпнкебярбн аюупеим', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('762', 'TJ', 'TJK', 'TAJIKISTAN', 'рюдфхйхярюм', 'пеяосакхйю рюдфхйхярюм', '10,11,12,97', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('384', 'CI', 'CIV', 'COTE D''IVOIRE', 'йнр д''хбсюп', 'пеяосакхйю йнр д''хбсюп', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('191', 'HR', 'HRV', 'CROATIA', 'унпбюрхъ', 'пеяосакхйю унпбюрхъ', '40,21,96,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('598', 'PG', 'PNG', 'PAPUA NEW GUINEA', 'оюосю мнбюъ цбхмеъ', 'мегюбхяхлне цнясдюпярбн оюосю мнбюъ цбхмеъ', '50,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('706', 'SO', 'SOM', 'SOMALIA', 'янлюкх', 'тедепюрхбмюъ пеяосакхйю янлюкх', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('051', 'AM', 'ARM', 'ARMENIA', 'юплемхъ', 'пеяосакхйю юплемхъ', '10,14', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('112', 'BY', 'BLR', 'BELARUS', 'аекюпсяэ', 'пеяосакхйю аекюпсяэ', '10,11,12,13,14,98,97', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('643', 'RU', 'RUS', 'RUSSIAN', 'пняяхъ', 'пняяхияйюъ тедепюжхъ', '10,11,50,12,13,14,98,97', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('462', 'MV', 'MDV', 'MALDIVES', 'люкэдхбш', 'люкэдхбяйюъ пеяосакхйю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('882', 'WS', 'WSM', 'SAMOA', 'яюлню', 'мегюбхяхлне цнясдюпярбн яюлню', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('728', 'SS', 'SSD', 'SOUTH SUDAN', 'чфмши ясдюм', 'пеяосакхйю чфмши ясдюм', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('417', 'KG', 'KGZ', 'KYRGYZSTAN', 'йхпцхгхъ', 'йхпцхгяйюъ пеяосакхйю', '10,11,12,14,97', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('804', 'UA', 'UKR', 'UKRAINE', 'сйпюхмю', 'сйпюхмю', '96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('270', 'GM', 'GMB', 'GAMBIA', 'цюлахъ', 'хякюляйюъ пеяосакхйю цюлахъ', '23,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('203', 'CZ', 'CZE', 'CZECH REPUBLIC', 'веухъ', 'веьяйюъ пеяосакхйю', '40,20,21,96', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('398', 'KZ', 'KAZ', 'KAZAKHSTAN', 'йюгюуярюм', 'пеяосакхйю йюгюуярюм', '10,11,12,13,14,98,97', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('266', 'GA', 'GAB', 'GABON', 'цюанм', 'цюанмяйюъ пеяосакхйю', '23,30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('226', 'GQ', 'GNQ', 'EQUATORIAL GUINEA', 'щйбюрнпхюкэмюъ цбхмеъ', 'пеяосакхйю щйбюрнпхюкэмюъ цбхмеъ', '23,30,92', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('360', 'ID', 'IDN', 'INDONESIA', 'хмднмегхъ', 'пеяосакхйю хмднмегхъ', '50,30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('364', 'IR', 'IRN', 'IRAN', 'хпюм (хякюляйюъ пеяосакхйю)', 'хякюляйюъ пеяосакхйю хпюм', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('663', 'MF', 'MAF', 'SAINT MARTIN', 'яем-люпрем (тпюмжсгяйюъ вюярэ)', 'яем-люпрем (тпюмжсгяйюъ вюярэ)', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('795', 'TM', 'TKM', 'TURKMENISTAN', 'рспйлемхярюм', 'рспйлемхярюм', '10', 1.0, 0.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('862', 'VE', 'VEN', 'VENEZUELA', 'бемеясщкю (анкхбюпхюмяйюъ пеяосакхйю)', 'анкхбюпхюмяйюъ пеяосакхйю бемеясщкю', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('092', 'VG', 'VGB', 'VIRGIN ISLANDS', 'бхпцхмяйхе нярпнбю (апхрюмяйхе)', 'апхрюмяйхе бхпцхмяйхе нярпнбю', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('850', 'VI', 'VIR', 'VIRGIN ISLANDS (U.S.)', 'бхпцхмяйхе нярпнбю (яью)', 'бхпцхмяйхе нярпнбю янедхмеммшу ьрюрнб', '23', 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('434', 'LY', 'LBY', 'LIBYAN', 'кхбхъ', 'цНЯСДЮПЯРБН кХБХЪ', '30,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('748', 'SZ', 'SWZ', 'ESWATINI', 'щябюрхмх', 'йнпнкебярбн щябюрхмх', '23,91', 1.0, 0.75);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('000', '00', NULL, 'мехгбеярмю', 'мехгбеярмю', 'мехгбеярмю', NULL, 1.0, 1.0);
INSERT INTO oksmt (KOD, ABC2, ABC3, ANAIM, KRNAIM, NAIM, KOD_AR, IMPORT, S_IMPORT) VALUES ('EUR', 'EU', NULL, NULL, 'ебпнянчг', 'ебпноеияйхи янчг', '21', 1.0, 1.0);

-- хМДЕЙЯ: FI_oksmt_0
CREATE INDEX FI_oksmt_0 ON oksmt (abc2);

-- хМДЕЙЯ: FI_oksmt_1
CREATE INDEX FI_oksmt_1 ON oksmt (kod_ar);

-- хМДЕЙЯ: FI_oksmt_2
CREATE INDEX FI_oksmt_2 ON oksmt (krnaim);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
